export const FETCH_BEERS = 'beers/FETCH_BEERS';
export const FETCH_FAVORITE_BEERS = 'beers/FETCH_FAVORITE_BEERS';
export const FETCH_BEER_DETAILS = 'beers/FETCH_BEER_DETAILS';
export const FETCH_BEERS_FAILED = 'beers/FETCH_BEERS_FAILED';
